# Generated by Django 4.1.3 on 2022-11-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_latitude_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
